Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -28,53 +28,69 @@ jobs:
       - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.1
         id: terraform_upload
         with:
-          workspace: ${{ vars.TF_WORKSPACE }}
+          workspace: ${{ env.TF_WORKSPACE }}
           directory: ${{ iac_config }}
           speculative: true
-          TF_WORKSPACE: "${{ vars.TF_WORKSPACE }}"
-          TF_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
-          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN}}
-          TF_HOSTNAME: ${{ env.TF_HOSTNAME }}
-          BUILD_FOLDER: "iac_config"
-          TF_RUN_CODE: "${{ github.head_ref }} & PR #${{ github.event.number }}"
 
-      - name: Update PR
-        uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        id: plan-comment
+      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
+        id: run
+        continue-on-error: true
         with:
-          github-token: ${{ secrets.G_TOKEN }}
+          workspace: ${{ env.TF_WORKSPACE }}
+          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
+          plan_only: true
+
+      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.1
+        id: plan-output
+        with:
+          plan: ${{ steps.run.outputs.plan_id }}
+
+      - uses: actions/github-script@v6
+        if: github.event_name == 'pull_request'
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             // 1. Retrieve existing bot comments for the PR
             const { data: comments } = await github.rest.issues.listComments({
               owner: context.repo.owner,
               repo: context.repo.repo,
               issue_number: context.issue.number,
-            });
+            })
             const botComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
-            });
-            const output = `#### Terraform Cloud Plan Output
-            \`\`\`
-            ${{ steps.speculative-plan.outputs.OUTPUT1_MESSAGE }}
-            ${{ steps.speculative-plan.outputs.OUTPUT2_MESSAGE }}
-            \`\`\`
-            [Terraform Cloud Plan](${{ steps.speculative-plan.outputs.TFE_RUN_URL }})
-            `;
-            // 3. Delete previous comment so PR timeline makes sense
+              return comment.user.type === 'Bot' && comment.body.includes('HCP Terraform Plan Output')
+            })
+            const output = `#### HCP Terraform Plan Output
+               \`\`\`\n
+               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
+               \`\`\`
+               [HCP Terraform Plan](${{ steps.run.outputs.run_link }})
+               `
+            // 3. If we have a comment, update it, otherwise create a new one
             if (botComment) {
-              github.rest.issues.deleteComment({
+              github.rest.issues.updateComment({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 comment_id: botComment.id,
-              });
+                body: output
+              })
+            } else {
+              github.rest.issues.createComment({
+                issue_number: context.issue.number,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                body: output
+              })
             }
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            });
+
+        ## Check Run Status, if not planned_and_finished fail the job
+      - id: terraform-cloud-check-run-status
+        if: ${{ steps.run.outputs.run_status != 'planned_and_finished'}}
+        run: |
+          echo "HCP Terraform Run Failed or Requires Further Attention"
+          echo "Run Status: '${{ steps.run.outputs.run_status }}'"
+          echo "${{ steps.run.outputs.run_link }}"
+          exit 1
+
 
   DEV_APPLY:
     name: Terraform Dev Provision
